### ISSUE TITLE
如何针对某类任务（如：ServiceTask），固化其部分属性

### ISSUE THREAD

**Issue by SnoopyoFifi** [imdwpeng/bpmn-editor#1]

**Comment by imdwpeng** [comment]
固话属性是什么意思？有具体场景吗？

**Comment by SnoopyoFifi** [comment]
给属性添加默认值，不用每次手动输入

**Comment by imdwpeng** [comment]
![微信图片_20190402104904](https://user-images.githubusercontent.com/19651568/55372682-2aba7080-5535-11e9-8c94-947c9c452565.png)
添加默认值的话，可以试试这种方法
